<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE sqlMap
    PUBLIC "-//ibatis.apache.org//DTD SQL Map 2.0//EN"
    "http://ibatis.apache.org/dtd/sql-map-2.dtd">

<%@ page import="org.tuckey.ibatis.implgen.*" %>
<%! public ParsedClass parsedClass; %>

<!--

  Generated implementation of <%= parsedClass.getFullyQualifiedName() %>
 
  Generated by ibatis-implgen
  http://code.google.com/p/ibatis-implgen/

  DO NOT EDIT

-->
<sqlMap namespace="<%= parsedClass.getFullyQualifiedName() %>">

    <% for (ParsedCacheModel cacheModel : parsedClass.getCacheModels()) { %>
    <cacheModel id="<%= cacheModel.getId() %>" type="<%= cacheModel.getType() %>">
        <% if ( cacheModel.isFlushInterval() ) { %><flushInterval hours="<%= cacheModel.getFlushIntervalHours() %>" /><% } %>
    </cacheModel>
    <% } %>

    <% for (ParsedResultMap resultMap : parsedClass.getResultMaps()) { %>
        <% if ( Util.empty(resultMap.getJavaClass())) { continue; } %>
    <resultMap id="<%= resultMap.getId() %>" class="<%= resultMap.getJavaClass() %>" <%--
            --%><% if ( resultMap.isAnyExtendsMap() ) { %> extends="<%= resultMap.getExtendsMap() %>" <% } %> ><%--
        --%><% for (ParsedResult result : resultMap.getResults()) { %>
        <result property="<%= result.getProperty() %>" <%--
                --%><% if ( !Util.empty(result.getJavaType()) ) { %> javaType="<%= result.getJavaType() %>" <% } %><%--
                --%> column="<%= result.getColumn() %>"<%--
                --%><% if ( !Util.empty(result.getJdbcType()) ) { %> jdbcType="<%= result.getJdbcType() %>" <% } %><%--
                --%><% if ( result.isAnyNullValue() ) { %> nullValue="<%= result.getNullValue() %>" <% } %> /><%--
        --%><% } %>
    </resultMap>
    <% } %>


    <% for (ParsedMethod method : parsedClass.getMethods()) { %>
        <% if ( ParsedMethod.Type.SELECT.equals(method.getType()) ) { %>
    <select id="<%= method.getName() %>" <%--
            --%><% if ( method.isAnyParameterClass() ) { %> parameterClass="<%= method.getParameterClass() %>" <% } %><%--
            --%><% if ( method.isAnyCacheModel() ) { %> cacheModel="<%= method.getCacheModel() %>" <% } %><%--
            --%><% if ( method.isAnyResultMap() ) { %> resultMap="<%= method.getResultMap() %>" <% } %><%--
            --%><% if ( method.isAnyResultClass() ) { %> resultClass="<%= method.getReturnsType() %>" <% } %> >
        <%= method.getSqlEscaped() %>
    </select>

        <% } else if ( ParsedMethod.Type.UPDATE.equals(method.getType()) ) { %>
    <update id="<%= method.getName() %>" <%--
                --%><% if ( method.isAnyParameters() ) { %> parameterClass="<%= method.getParameterClass() %>" <% } %>  >
        <%= method.getSqlEscaped() %>
    </update>

        <% } else if ( ParsedMethod.Type.DELETE.equals(method.getType()) ) { %>
    <delete id="<%= method.getName() %>" <%--
            --%><% if ( method.isAnyParameters() ) { %> parameterClass="<%= method.getParameterClass() %>" <% } %>   >
        <%= method.getSqlEscaped() %>
    </delete>

        <% } else if ( ParsedMethod.Type.INSERT.equals(method.getType()) ) { %>
    <insert id="<%= method.getName() %>" <%--
            --%><% if ( method.isAnyParameters() ) { %> parameterClass="<%= method.getParameterClass() %>" <% } %>  >
        <%= method.getSqlEscaped() %>
    </insert>

        <% } else if ( ParsedMethod.Type.PROCEDURE.equals(method.getType()) ) { %>
    <procedure id="<%= method.getName() %>" <%--
               --%><% if ( method.isAnyParameterClass() ) { %> parameterClass="<%= method.getParameterClass() %>" <% } %><%--
               --%><% if ( method.isAnyCacheModel() ) { %> cacheModel="<%= method.getCacheModel() %>" <% } %><%--
               --%><% if ( method.isAnyResultMap() ) { %> resultMap="<%= method.getResultMap() %>" <% } %><%--
               --%><% if ( method.isAnyResultClass() ) { %> resultClass="<%= method.getReturnsType() %>" <% } %>  >
        <%= method.getSqlEscaped() %>
    </procedure>

        <% } else { // ParsedMethod.Type.STATEMENT %>
    <statement id="<%= method.getName() %>" <%--
           --%><% if ( method.isAnyParameterClass() ) { %> parameterClass="<%= method.getParameterClass() %>" <% } %><%--
           --%><% if ( method.isAnyCacheModel() ) { %> cacheModel="<%= method.getCacheModel() %>" <% } %><%--
           --%><% if ( method.isAnyResultMap() ) { %> resultMap="<%= method.getResultMap() %>" <% } %><%--
           --%><% if ( method.isAnyResultClass() ) { %> resultClass="<%= method.getReturnsType() %>" <% } %>  >
        <%= method.getSqlEscaped() %>
    </statement>

        <% } %>
    <% } %>

</sqlMap>

